name: trylinks.js CI

on:
  workflow_dispatch:
  push:
    branches: [feat/implement-pipeline]
  pull_request:
    branches: [feat/implement-pipeline]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.18.1]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and build client
      run: |
        cd client
        npm i
        npm run build
    - name: Install server dependencies
      run: |
        cd server
        npm i
    - name: Start server
      run: |
        cd server
        npm start
      env:
        DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        SECRET: ${{ secrets.SECRET }}
        TRYLINKS_CONFIG: ${{ secrets.TRYLINKS_CONFIG }}
        PROD_DOMAIN: ${{ secrets.PROD_DOMAIN }}
        COMPILE_WAIT_TIME: ${{ secrets.COMPILE_WAIT_TIME }}
        HOST: ${{ secrets.HOST }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
        PORT: ${{ secrets.PORT }}