name: trylinks-cicd-develop.js CI

on:
  workflow_dispatch:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]


jobs:
  build:
    runs-on: dev
    environment: develop

    strategy:
      matrix:
        node-version: [18.18.1]

    env:
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
      SECRET: ${{ secrets.SECRET }}
      TRYLINKS_CONFIG: ${{ secrets.TRYLINKS_CONFIG }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      COMPILE_WAIT_TIME: ${{ vars.COMPILE_WAIT_TIME }}
      HOST: ${{ vars.HOST }}
      NODE_ENV: ${{ vars.NODE_ENV }}
      PROD_ORIGIN: ${{vars.PROD_ORIGIN}}
      PROD_DOMAIN: ${{vars.PROD_ORIGIN}}
      AUTH_DOMAIN: ${{vars.AUTH_DOMAIN}}
      PROD_AUTH_CLIENT_ID: ${{vars.PROD_AUTH_CLIENT_ID}}
      PROD_AUTH_REDIRECT_URI: ${{vars.PROD_AUTH_REDIRECT_URI}}


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Add linx to PATH
      run: echo "/home/testuser/.opam/4.08.0/bin" >> $GITHUB_PATH
    - name: Install client dependencies
      run: |
        cd client
        npm i
    - name: Run Angular Tests
      run: |
        cd client
        npm test -- --watch=false --browsers=ChromeHeadless
    - name: Build client
      run: |
        cd client

        npm run build -- --configuration ${{ env.NODE_ENV }}
    - name: Install server dependencies
      run: |
        cd server
        npm i
    - name: Stop previous server instance
      run: pm2 stop 0
    - name: Start server with PM2
      run: pm2 start 0 --update-env
    - name: Save PM2 configuration
      run: pm2 save
    - name: Restart Nginx
      run: sudo service nginx restart
    - name: Run e2e tests
      run: |
        cd e2e_tests
        npm i
        npx cypress run